In [1]:
import pandas as pd
df = pd.read_csv("ga.csv")

In [2]:
df

,channelGrouping,date,device,fullVisitorId,geoNetwork,sessionId,socialEngagementType,totals,trafficSource,visitId,visitNumber,visitStartTime
0,Direct,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",6.194190e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",6194193421514403509_1472843572,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""11"", ""pageviews"": ""11...","{""campaign"": ""(not set)"", ""source"": ""(direct)""...",1472843572,1,1472843572
1,Organic Search,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",5.327170e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",5327166854580374902_1472844906,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""11"", ""pageviews"": ""10...","{""campaign"": ""(not set)"", ""source"": ""google"", ...",1472844906,3,1472844906
2,Referral,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",8.885050e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",8885051388942907862_1472827393,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""13"", ""pageviews"": ""11...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1472827393,7,1472827393
3,Referral,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",1.854680e+17,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",0185467632009737931_1472846398,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""13"", ""pageviews"": ""12...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1472846398,6,1472846398
4,Referral,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",3.244890e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",3244885836845029978_1472824817,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""17"", ""pageviews"": ""14...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1472824817,4,1472824817
...,...,...,...,...,...,...,...,...,...,...,...,...
11510,Referral,20170104,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",6.849600e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",6849604863010168468_1483566314,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""61"", ""pageviews"": ""48...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1483566314,10,1483566314
11511,Referral,20170104,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",2.119870e+17,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",0211986650009953276_1483568879,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""66"", ""pageviews"": ""30...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1483568879,2,1483568879
11512,Referral,20170104,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",9.981560e+18,"{""continent"": ""Asia"", ""subContinent"": ""Eastern...",9981562221973608723_1483576938,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""122"", ""pageviews"": ""9...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1483576938,1,1483576938
11513,Direct,20170104,"{""browser"": ""Firefox"", ""browserVersion"": ""not ...",9.631260e+17,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",963126344221316701_1483552674,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""130"", ""pageviews"": ""9...","{""campaign"": ""(not set)"", ""source"": ""(direct)""...",1483552674,3,1483552674
11514,Direct,20170104,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",9.771440e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",9771437221362506189_1483538997,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""237"", ""pageviews"": ""1...","{""campaign"": ""(not set)"", ""source"": ""(direct)""...",1483538997,12,1483538997

## struct
    - key- value  여러 개의 쌍을 포함하는 객체 ,딕셔너리처럼 작동 , json 기준 = {"browser": "Firefox", 'OS' : 'Android'}
## array
    - 여러 개의 값을 포함하는 리스트(list)형태의 데이터, 단순 값으로도 들어갈 수 있지만 -> struct 으로 들어갈 수 있다. 
        - 'items' :[{'id':111, {'id':112}]|

In [3]:
data = {
    'user_id':[1,2],
    'device':[
        {'browser':'Chrome', 'os':'Windows'}, ## sturct
        {'browser':'Safari', 'os':'MacOS'},
    ],
    'interests':[
        ['sports','music'], #array
        ['movie','travel']
    ],
    'purchase':[
        [{'item':'apple','price':1.5}, {'item':'watch','price':1.0}], ## array of struct
        [{'item':'banana', 'price':1.3}]   
    ]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
##struct 컬럼을 파싱하는 방법
device_df = df['device'].apply(pd.Series) # 둘을 분리할 수 있다.

In [6]:
df

,user_id,device,interests,purchase
0,1,"{'browser': 'Chrome', 'os': 'Windows'}","[sports, music]","[{'item': 'apple', 'price': 1.5}, {'item': 'wa..."
1,2,"{'browser': 'Safari', 'os': 'MacOS'}","[movie, travel]","[{'item': 'banana', 'price': 1.3}]"

In [7]:
# Array 컬럼 (interest) explode

df.explode('interests') #['interests'} == 'music'

,user_id,device,interests,purchase
0,1,"{'browser': 'Chrome', 'os': 'Windows'}",sports,"[{'item': 'apple', 'price': 1.5}, {'item': 'wa..."
0,1,"{'browser': 'Chrome', 'os': 'Windows'}",music,"[{'item': 'apple', 'price': 1.5}, {'item': 'wa..."
1,2,"{'browser': 'Safari', 'os': 'MacOS'}",movie,"[{'item': 'banana', 'price': 1.3}]"
1,2,"{'browser': 'Safari', 'os': 'MacOS'}",travel,"[{'item': 'banana', 'price': 1.3}]"

In [8]:
# Array of Sturct 컴럼만들기
df_pr = df.explode('purchase')

In [9]:
pr_details = df_pr['purchase'].apply(pd.Series)

In [10]:
pd.concat([df_pr.drop(columns = ['purchase']), pr_details.add_prefix('purchase_')], axis = 1)

,user_id,device,interests,purchase_item,purchase_price
0,1,"{'browser': 'Chrome', 'os': 'Windows'}","[sports, music]",apple,1.5
0,1,"{'browser': 'Chrome', 'os': 'Windows'}","[sports, music]",watch,1.0
1,2,"{'browser': 'Safari', 'os': 'MacOS'}","[movie, travel]",banana,1.3

In [11]:
df = pd.read_csv("ga.csv")

In [12]:
df

,channelGrouping,date,device,fullVisitorId,geoNetwork,sessionId,socialEngagementType,totals,trafficSource,visitId,visitNumber,visitStartTime
0,Direct,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",6.194190e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",6194193421514403509_1472843572,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""11"", ""pageviews"": ""11...","{""campaign"": ""(not set)"", ""source"": ""(direct)""...",1472843572,1,1472843572
1,Organic Search,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",5.327170e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",5327166854580374902_1472844906,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""11"", ""pageviews"": ""10...","{""campaign"": ""(not set)"", ""source"": ""google"", ...",1472844906,3,1472844906
2,Referral,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",8.885050e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",8885051388942907862_1472827393,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""13"", ""pageviews"": ""11...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1472827393,7,1472827393
3,Referral,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",1.854680e+17,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",0185467632009737931_1472846398,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""13"", ""pageviews"": ""12...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1472846398,6,1472846398
4,Referral,20160902,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",3.244890e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",3244885836845029978_1472824817,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""17"", ""pageviews"": ""14...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1472824817,4,1472824817
...,...,...,...,...,...,...,...,...,...,...,...,...
11510,Referral,20170104,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",6.849600e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",6849604863010168468_1483566314,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""61"", ""pageviews"": ""48...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1483566314,10,1483566314
11511,Referral,20170104,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",2.119870e+17,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",0211986650009953276_1483568879,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""66"", ""pageviews"": ""30...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1483568879,2,1483568879
11512,Referral,20170104,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",9.981560e+18,"{""continent"": ""Asia"", ""subContinent"": ""Eastern...",9981562221973608723_1483576938,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""122"", ""pageviews"": ""9...","{""referralPath"": ""/"", ""campaign"": ""(not set)"",...",1483576938,1,1483576938
11513,Direct,20170104,"{""browser"": ""Firefox"", ""browserVersion"": ""not ...",9.631260e+17,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",963126344221316701_1483552674,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""130"", ""pageviews"": ""9...","{""campaign"": ""(not set)"", ""source"": ""(direct)""...",1483552674,3,1483552674
11514,Direct,20170104,"{""browser"": ""Chrome"", ""browserVersion"": ""not a...",9.771440e+18,"{""continent"": ""Americas"", ""subContinent"": ""Nor...",9771437221362506189_1483538997,Not Socially Engaged,"{""visits"": ""1"", ""hits"": ""237"", ""pageviews"": ""1...","{""campaign"": ""(not set)"", ""source"": ""(direct)""...",1483538997,12,1483538997

In [13]:
df['device']

0        {"browser": "Chrome", "browserVersion": "not a...
1        {"browser": "Chrome", "browserVersion": "not a...
2        {"browser": "Chrome", "browserVersion": "not a...
3        {"browser": "Chrome", "browserVersion": "not a...
4        {"browser": "Chrome", "browserVersion": "not a...
                               ...
11510    {"browser": "Chrome", "browserVersion": "not a...
11511    {"browser": "Chrome", "browserVersion": "not a...
11512    {"browser": "Chrome", "browserVersion": "not a...
11513    {"browser": "Firefox", "browserVersion": "not ...
11514    {"browser": "Chrome", "browserVersion": "not a...
Name: device, Length: 11515, dtype: object

In [14]:
df['totals'].apply(pd.Series)

                                                       0
0      {"visits": "1", "hits": "11", "pageviews": "11...
1      {"visits": "1", "hits": "11", "pageviews": "10...
2      {"visits": "1", "hits": "13", "pageviews": "11...
3      {"visits": "1", "hits": "13", "pageviews": "12...
4      {"visits": "1", "hits": "17", "pageviews": "14...
...                                                  ...
11510  {"visits": "1", "hits": "61", "pageviews": "48...
11511  {"visits": "1", "hits": "66", "pageviews": "30...
11512  {"visits": "1", "hits": "122", "pageviews": "9...
11513  {"visits": "1", "hits": "130", "pageviews": "9...
11514  {"visits": "1", "hits": "237", "pageviews": "1...

[11515 rows x 1 columns]

### 마케팅 Source, Medium별 성과 비교
    - trafficSource, totals

### 간단한 시각화

In [7]:
import json 

df=pd.read_csv('ga.csv')
##totals 풀기
df['totals']=df['totals'].apply(json.loads)
#trafficSource -> source, medium dict 객체로 변환해서 가지고 와야 한다.
df['trafficSource'] = df['trafficSource'].apply(json.loads)

## 수치형 컬럼을 추출을 해야 한다.
df['pageviews']=df['totals'].apply(lambda x : int(x.get('pageviews'),0))
df['hits']=df['totals'].apply(lambda x : int(x.get('hits'),0))
df['visits']=df['totals'].apply(lambda x : int(x.get('visits'),0))

## campaign, source, medium을 가지고 오자!
df['campaign']=df['trafficSource'].apply(lambda x : x.get('campaign','(not set)'))
df['source']=df['trafficSource'].apply(lambda x : x.get('source','(not set)'))
df['medium']=df['trafficSource'].apply(lambda x : x.get('medium','(not set)'))

## 집계
agg_df_sm=df.groupby(['date','source','medium'])[['pageviews','hits','visits']].sum().reset_index()

In [8]:
agg_df_sm

          date               source    medium  pageviews  hits  visits
0     20160801             (direct)    (none)        341   441       8
1     20160801         basecamp.com  referral         49    69       1
2     20160801       gatewaycdi.com  referral         14    18       1
3     20160801               google   organic        216   372       7
4     20160801  mall.googleplex.com  referral        428   568      16
...        ...                  ...       ...        ...   ...     ...
1753  20170801               google       cpc         20    28       1
1754  20170801               google       cpm          5     5       1
1755  20170801               google   organic        244   319       6
1756  20170801      mail.google.com  referral         16    16       1
1757  20170801  mall.googleplex.com  referral        780  1083      26

[1758 rows x 6 columns]

In [9]:
## 데이터의 검증은 어떤 식으로 하면 될까?
## agg_df_sm 집계된 테이블  vs 원천이랑 비교하면 된다. ga.csv 이 둘의 값이 같으면 정상이고, 다르면 잘못된 것
## 검증 전 애가  join 또는 추출할 데이터의 타입을 맞춰줘야 한다. 공백도 제거하고, 타입도 맞추고

# 원본데이터 타입 변경 및 공백변경
df['date'] = df['date'].astype(str)
df['source'] = df['source'].str.strip()
df['medium'] = df['medium'].str.strip()

# 집계데이터 타입 변경 및 공백 변경
agg_df_sm['date'] = agg_df_sm['date'].astype(str)
agg_df_sm['source'] = agg_df_sm['source'].str.strip()
agg_df_sm['medium'] = agg_df_sm['medium'].str.strip()

## Step1
## 검증할 조건을 변수로 만들기
val_date = '20170801'
val_source = 'google'
val_medium = 'organic'

## Step2
## 원천 데이터를  df로 추출하기
origin_sum = df[
    (df['date']==val_date) &
    (df['source']==val_source)&
    (df['medium']==val_medium)
][['pageviews', 'hits', 'visits']].sum()

## Step3
## 집계된 테이블에서 추출하기
agg_sum = agg_df_sm[
    (agg_df_sm['date']==val_date) &
    (agg_df_sm['source']==val_source) &
    (agg_df_sm['medium']==val_medium)
][['pageviews', 'hits', 'visits']]

In [10]:
origin_sum

pageviews    244
hits         319
visits         6
dtype: int64

In [11]:
agg_sum

      pageviews  hits  visits
1755        244   319       6

In [12]:
## plotly 시각화로 medium -> source으로
import plotly.express as px

fig = px.sunburst(
    agg_df_sm, 
    path = ['medium', 'source'],
    values = 'pageviews',
    color = 'pageviews',
    color_continuous_scale = 'Blues'

SyntaxError: incomplete input (3088137572.py, line 10)